// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: pkg/clientpb/client.proto

package clientpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KvdbClient is the client API for Kvdb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvdbClient interface {
	Leader(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Ready(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Response, error)
	Change(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Response, error)
}

type kvdbClient struct {
	cc grpc.ClientConnInterface
}

func NewKvdbClient(cc grpc.ClientConnInterface) KvdbClient {
	return &kvdbClient{cc}
}

func (c *kvdbClient) Leader(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/clientpb.Kvdb/leader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvdbClient) Ready(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/clientpb.Kvdb/ready", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvdbClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/clientpb.Kvdb/put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvdbClient) Change(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/clientpb.Kvdb/change", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvdbServer is the server API for Kvdb service.
// All implementations must embed UnimplementedKvdbServer
// for forward compatibility
type KvdbServer interface {
	Leader(context.Context, *Request) (*Response, error)
	Ready(context.Context, *Request) (*Response, error)
	Put(context.Context, *PutRequest) (*Response, error)
	Change(context.Context, *ConfigRequest) (*Response, error)
	mustEmbedUnimplementedKvdbServer()
}

// UnimplementedKvdbServer must be embedded to have forward compatible implementations.
type UnimplementedKvdbServer struct {
}

func (UnimplementedKvdbServer) Leader(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leader not implemented")
}
func (UnimplementedKvdbServer) Ready(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedKvdbServer) Put(context.Context, *PutRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKvdbServer) Change(context.Context, *ConfigRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Change not implemented")
}
func (UnimplementedKvdbServer) mustEmbedUnimplementedKvdbServer() {}

// UnsafeKvdbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvdbServer will
// result in compilation errors.
type UnsafeKvdbServer interface {
	mustEmbedUnimplementedKvdbServer()
}

func RegisterKvdbServer(s grpc.ServiceRegistrar, srv KvdbServer) {
	s.RegisterService(&Kvdb_ServiceDesc, srv)
}

func _Kvdb_Leader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvdbServer).Leader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientpb.Kvdb/leader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvdbServer).Leader(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvdb_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvdbServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientpb.Kvdb/ready",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvdbServer).Ready(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvdb_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvdbServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientpb.Kvdb/put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvdbServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvdb_Change_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvdbServer).Change(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientpb.Kvdb/change",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvdbServer).Change(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kvdb_ServiceDesc is the grpc.ServiceDesc for Kvdb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kvdb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clientpb.Kvdb",
	HandlerType: (*KvdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "leader",
			Handler:    _Kvdb_Leader_Handler,
		},
		{
			MethodName: "ready",
			Handler:    _Kvdb_Ready_Handler,
		},
		{
			MethodName: "put",
			Handler:    _Kvdb_Put_Handler,
		},
		{
			MethodName: "change",
			Handler:    _Kvdb_Change_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/clientpb/client.proto",
}
