// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: pkg/raftpb/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_NORMAL        EntryType = 0
	EntryType_MEMBER_CHNAGE EntryType = 1
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "NORMAL",
		1: "MEMBER_CHNAGE",
	}
	EntryType_value = map[string]int32{
		"NORMAL":        0,
		"MEMBER_CHNAGE": 1,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_raftpb_raft_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_pkg_raftpb_raft_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_raftpb_raft_proto_rawDescGZIP(), []int{0}
}

type MemberChangeType int32

const (
	MemberChangeType_ADD_NODE    MemberChangeType = 0
	MemberChangeType_REMOVE_NODE MemberChangeType = 1
)

// Enum value maps for MemberChangeType.
var (
	MemberChangeType_name = map[int32]string{
		0: "ADD_NODE",
		1: "REMOVE_NODE",
	}
	MemberChangeType_value = map[string]int32{
		"ADD_NODE":    0,
		"REMOVE_NODE": 1,
	}
)

func (x MemberChangeType) Enum() *MemberChangeType {
	p := new(MemberChangeType)
	*p = x
	return p
}

func (x MemberChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_raftpb_raft_proto_enumTypes[1].Descriptor()
}

func (MemberChangeType) Type() protoreflect.EnumType {
	return &file_pkg_raftpb_raft_proto_enumTypes[1]
}

func (x MemberChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberChangeType.Descriptor instead.
func (MemberChangeType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_raftpb_raft_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_VOTE              MessageType = 0
	MessageType_VOTE_RES          MessageType = 1
	MessageType_HEARTBEAT         MessageType = 2
	MessageType_HEARTBEAT_RESP    MessageType = 3
	MessageType_APPEND_ENTRY      MessageType = 4
	MessageType_APPEND_ENTRY_RESP MessageType = 5
	MessageType_PROPOSE           MessageType = 6
	MessageType_PROPOSE_RESP      MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "VOTE",
		1: "VOTE_RES",
		2: "HEARTBEAT",
		3: "HEARTBEAT_RESP",
		4: "APPEND_ENTRY",
		5: "APPEND_ENTRY_RESP",
		6: "PROPOSE",
		7: "PROPOSE_RESP",
	}
	MessageType_value = map[string]int32{
		"VOTE":              0,
		"VOTE_RES":          1,
		"HEARTBEAT":         2,
		"HEARTBEAT_RESP":    3,
		"APPEND_ENTRY":      4,
		"APPEND_ENTRY_RESP": 5,
		"PROPOSE":           6,
		"PROPOSE_RESP":      7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_raftpb_raft_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pkg_raftpb_raft_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_raftpb_raft_proto_rawDescGZIP(), []int{2}
}

type LogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  EntryType `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.EntryType" json:"type,omitempty"`
	Term  uint64    `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	Index uint64    `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	Data  []byte    `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_raftpb_raft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_raftpb_raft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_raftpb_raft_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_NORMAL
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MemberChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    MemberChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.MemberChangeType" json:"type,omitempty"`
	Id      uint64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Address string           `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *MemberChange) Reset() {
	*x = MemberChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_raftpb_raft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberChange) ProtoMessage() {}

func (x *MemberChange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_raftpb_raft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberChange.ProtoReflect.Descriptor instead.
func (*MemberChange) Descriptor() ([]byte, []int) {
	return file_pkg_raftpb_raft_proto_rawDescGZIP(), []int{1}
}

func (x *MemberChange) GetType() MemberChangeType {
	if x != nil {
		return x.Type
	}
	return MemberChangeType_ADD_NODE
}

func (x *MemberChange) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberChange) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MemberChangeCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changes []*MemberChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *MemberChangeCollection) Reset() {
	*x = MemberChangeCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_raftpb_raft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberChangeCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberChangeCollection) ProtoMessage() {}

func (x *MemberChangeCollection) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_raftpb_raft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberChangeCollection.ProtoReflect.Descriptor instead.
func (*MemberChangeCollection) Descriptor() ([]byte, []int) {
	return file_pkg_raftpb_raft_proto_rawDescGZIP(), []int{2}
}

func (x *MemberChangeCollection) GetChanges() []*MemberChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type RaftMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType      MessageType `protobuf:"varint,1,opt,name=MsgType,proto3,enum=raftpb.MessageType" json:"MsgType,omitempty"`
	Term         uint64      `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	From         uint64      `protobuf:"varint,3,opt,name=From,proto3" json:"From,omitempty"`
	To           uint64      `protobuf:"varint,4,opt,name=To,proto3" json:"To,omitempty"`
	LastLogIndex uint64      `protobuf:"varint,5,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm  uint64      `protobuf:"varint,6,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	LastCommit   uint64      `protobuf:"varint,7,opt,name=LastCommit,proto3" json:"LastCommit,omitempty"`
	Entry        []*LogEntry `protobuf:"bytes,8,rep,name=Entry,proto3" json:"Entry,omitempty"`
	Success      bool        `protobuf:"varint,9,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_raftpb_raft_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_raftpb_raft_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_pkg_raftpb_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RaftMessage) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_VOTE
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RaftMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RaftMessage) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RaftMessage) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RaftMessage) GetLastCommit() uint64 {
	if x != nil {
		return x.LastCommit
	}
	return 0
}

func (x *RaftMessage) GetEntry() []*LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *RaftMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_raftpb_raft_proto protoreflect.FileDescriptor

var file_pkg_raftpb_raft_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2f, 0x72, 0x61, 0x66,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x22,
	0x6f, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x72, 0x61, 0x66, 0x74,
	0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x66, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x48, 0x0a, 0x16, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x73, 0x22, 0x9c, 0x02, 0x0a, 0x0b, 0x52, 0x61, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x4c, 0x61, 0x73,
	0x74, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x20, 0x0a,
	0x0b, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x54, 0x65, 0x72, 0x6d, 0x12,
	0x1e, 0x0a, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12,
	0x26, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x2a, 0x2a, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a,
	0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x45,
	0x4d, 0x42, 0x45, 0x52, 0x5f, 0x43, 0x48, 0x4e, 0x41, 0x47, 0x45, 0x10, 0x01, 0x2a, 0x31, 0x0a,
	0x10, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x44, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x01,
	0x2a, 0x90, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x56, 0x4f, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x4f,
	0x54, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45, 0x41, 0x52,
	0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x45, 0x41, 0x52, 0x54,
	0x42, 0x45, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x41,
	0x50, 0x50, 0x45, 0x4e, 0x44, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x10, 0x04, 0x12, 0x15, 0x0a,
	0x11, 0x41, 0x50, 0x50, 0x45, 0x4e, 0x44, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x52, 0x45,
	0x53, 0x50, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x45, 0x10,
	0x06, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x10, 0x07, 0x32, 0x46, 0x0a, 0x0c, 0x52, 0x61, 0x66, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x12, 0x13, 0x2e, 0x72, 0x61,
	0x66, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x13, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x6b,
	0x76, 0x64, 0x62, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_raftpb_raft_proto_rawDescOnce sync.Once
	file_pkg_raftpb_raft_proto_rawDescData = file_pkg_raftpb_raft_proto_rawDesc
)

func file_pkg_raftpb_raft_proto_rawDescGZIP() []byte {
	file_pkg_raftpb_raft_proto_rawDescOnce.Do(func() {
		file_pkg_raftpb_raft_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_raftpb_raft_proto_rawDescData)
	})
	return file_pkg_raftpb_raft_proto_rawDescData
}

var file_pkg_raftpb_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_raftpb_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_raftpb_raft_proto_goTypes = []interface{}{
	(EntryType)(0),                 // 0: raftpb.EntryType
	(MemberChangeType)(0),          // 1: raftpb.MemberChangeType
	(MessageType)(0),               // 2: raftpb.MessageType
	(*LogEntry)(nil),               // 3: raftpb.LogEntry
	(*MemberChange)(nil),           // 4: raftpb.MemberChange
	(*MemberChangeCollection)(nil), // 5: raftpb.MemberChangeCollection
	(*RaftMessage)(nil),            // 6: raftpb.RaftMessage
}
var file_pkg_raftpb_raft_proto_depIdxs = []int32{
	0, // 0: raftpb.LogEntry.type:type_name -> raftpb.EntryType
	1, // 1: raftpb.MemberChange.type:type_name -> raftpb.MemberChangeType
	4, // 2: raftpb.MemberChangeCollection.changes:type_name -> raftpb.MemberChange
	2, // 3: raftpb.RaftMessage.MsgType:type_name -> raftpb.MessageType
	3, // 4: raftpb.RaftMessage.Entry:type_name -> raftpb.LogEntry
	6, // 5: raftpb.RaftInternal.send:input_type -> raftpb.RaftMessage
	6, // 6: raftpb.RaftInternal.send:output_type -> raftpb.RaftMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_raftpb_raft_proto_init() }
func file_pkg_raftpb_raft_proto_init() {
	if File_pkg_raftpb_raft_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_raftpb_raft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_raftpb_raft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_raftpb_raft_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberChangeCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_raftpb_raft_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_raftpb_raft_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_raftpb_raft_proto_goTypes,
		DependencyIndexes: file_pkg_raftpb_raft_proto_depIdxs,
		EnumInfos:         file_pkg_raftpb_raft_proto_enumTypes,
		MessageInfos:      file_pkg_raftpb_raft_proto_msgTypes,
	}.Build()
	File_pkg_raftpb_raft_proto = out.File
	file_pkg_raftpb_raft_proto_rawDesc = nil
	file_pkg_raftpb_raft_proto_goTypes = nil
	file_pkg_raftpb_raft_proto_depIdxs = nil
}
